print("Please enter the following information so i can sell it for a profit!")
print('\t')
a=input("First name:")
b=input("Last name:")
c=input("Grade (9-12):")
d=input("Student ID:")
e=input("Login:")
f=input("GPA (0.0-4.0):")
print('\t')

print("Your information:")
print('\t'f"Login:{b}")
print('\t'f"ID:{c}")
print('\t'f"NAme:{b}")
print('\t'f"GPA:{f}")
print('\t'f"Grade:{c}")
